name: Deploy

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: vishnu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/vishnu/invoiceGenerator/invoice-generator
            git fetch
            git pull origin main 